---
- name: Knowage
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - { role: common , tags: "common"} 
  - { role: mysql , tags: "mysql"}
  - { role: knowage  , tags: "knowage"} 
  - { role: nginx , tags: "nginx"}

    