---
- name: add Oracle JAVA PPA
  apt_repository:
    repo: ppa:webupd8team/java 

- name: Accept oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install Open JAVA
  apt:
    name: [openjdk-8-jdk]
    state: latest

- name: Download knowage
  unarchive:
    src: '{{knowage_download_url}}'
    dest: '{{ansible_user_dir}}'
    remote_src: yes
    mode: 0750
                                          
- name: Rename install package
  shell: mv Knowage-*  Knowage-CE-Installer-Unix.sh
  args:
    chdir: '{{ansible_user_dir}}'

- name: create dir
  file:
    path: /data/wwwroot/
    state: directory

- name: upload Install script
  template:
    src: install.sh
    dest: '{{ansible_user_dir}}'
    mode: 0750

- name: install Knowage
  shell: '{{ansible_user_dir}}/install.sh '     

- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'

- name: Create User for Knowage
  user:
    name: knowage
    create_home: no
    home: /data/wwwroot/Knowage-Server-CE
    shell: /usr/sbin/nologin

- name: Change Directory owner
  file:
    path: /data/wwwroot/Knowage-Server-CE
    state: directory
    owner: knowage
    group: knowage
    recurse: yes

- name: Change Directory owner
  file:
    path: /data/wwwroot/Knowage-Server-CE
    state: directory
    owner: knowage
    group: knowage
    recurse: yes

- name: Setting Knowage Service
  copy:
    src: knowage.service
    dest: /lib/systemd/system

- name: restart knowage
  service: name=knowage state=restarted enabled=yes


- name: Delete package
  file:
    path: "/root/{{item}}"
    state: absent
  with_items:
   - "install.sh"
   - "Knowage-CE-Installer-Unix.sh"

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/sites-available

- name: restart nginx
  service: name=nginx state=restarted enabled=yes