#1 pre-installation
- name: Create User for Knowage
  user:
    name: knowage
    home: /data/wwwroot/knowage
    shell: /usr/sbin/nologin

- name: Create /data/wwwroot/knowage
  file:
    path: /data/wwwroot/knowage
    state: directory
    owner: knowage
    group: knowage

- name: Ansible check file exists
  stat:
    path: "/data/wwwroot/knowage/Knowage-*.zip"
  register: result

- name: Download Knowage, it have 2G, need 10 minutes
  unarchive:
    src: "{{knowage_download_url}}"
    dest: "/data/wwwroot/knowage"
    remote_src: yes
    mode: 0750
  when: not result.stat.exists

#2 install Knowage by OS_family if need
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install Knowage
  shell: bash Knowage*.sh
  args:
    chdir: /data/wwwroot/knowage

#2 configure Knowage
- name: Change Directory owner
  file:
    path: /data/wwwroot/knowage
    state: directory
    owner: knowage
    group: knowage
    recurse: yes

- name: Setting Knowage Service
  copy:
    src: knowage.service
    dest: /lib/systemd/system/knowage.service

- name: restart knowage
  service: name=knowage state=restarted enabled=yes

- name: Delete package
  file:
    path: "/root/{{item}}"
    state: absent
  with_items:
   - "install.sh"
   - "Knowage-CE-Installer-Unix.sh"

- name: set reverse proxy
  copy: 
    src: default
    dest: /etc/nginx/sites-available

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

#3 set soft link, check version and service state

### ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/knowage  /data/wwwroot
    ln -sf /opt/knowage/config /data/config

### Check version
- block:
  - name: Check Knowage Version
    shell: sudo sh -c "rabbitmqctl status | grep 'Knowage version' 1>> /data/logs/install_version.txt"

### check service state
- name: Check Knowage Service
  shell: systemctl status knowage | grep Active*
  register: check_knowage_service
  notify: check_knowage_service